# COVID stream keywords (https://developer.twitter.com/en/docs/labs/covid19-stream/filtering-rules)
# Snapshot: May 13, 2020

KEYWORDS = [
    "#Coronavirusmexico",
    "#covid2019",
    "#coronavirususa",
    "#covid_19uk",
    "#covid-19uk",
    "#Briefing_COVID19",
    "#coronaapocolypse",
    "#coronavirusbrazil",
    "#marchapelocorona",
    "#coronavirusbrasil",
    "#coronaday",
    "#coronafest",
    "#coronavirusu",
    "#covid2019pt",
    "#COVID19PT",
    "#caronavirususa",
    "#covid19india",
    "#caronavirusindia",
    "#caronavirusoutbreak",
    "#caronavirus",
    "carona virus",
    "#2019nCoV",
    "2019nCoV",
    "#codvid_19",
    "#codvid19",
    "#conronaviruspandemic",
    "#corona",
    "corona",
    "corona vairus",
    "corona virus",
    "#coronadeutschland",
    "#Coronaferien",
    "#coronaflu",
    "#coronaoutbreak",
    "#coronapandemic",
    "#Coronapanik",
    "#coronapocalypse",
    "#CoronaSchlager",
    "#coronavid19",
    "#coronavid19",
    "#Coronavirus",
    "Coronavirus",
    "#coronavirusargentina",
    "#coronavirusbrasil",
    "#CoronaVirusCanada",
    "#coronaviruschile",
    "#coronaviruscolombia",
    "#CoronaVirusDE",
    "#coronavirusecuador",
    "#CoronavirusEnColombia",
    "#coronavirusespana",
    "CoronavirusFR",
    "#CoronavirusFR",
    "#coronavirusIndonesia",
    "#Coronavirusireland",
    "#CoronaVirusIreland",
    "#coronavirusmadrid",
    "#coronavirusmexico",
    "#coronavirusnobrasil",
    "#coronavirusnyc",
    "#coronavirusoutbreak",
    "#coronavirusoutbreak",
    "#coronaviruspandemic",
    "#coronavirusperu",
    "#coronaviruspuertorico",
    "#coronavirusrd",
    "#coronavirustruth",
    "#coronavirusuk",
    "coronavirusupdate",
    "#coronavirusupdates",
    "#coronavirusuruguay",
    "coronga virus",
    "corongavirus",
    "#Corvid19virus",
    "#covd19",
    "#covid",
    "covid",
    "#covid",
    "covid",
    "covid 19",
    "#covid_19",
    "#covid_19",
    "Covid_19",
    "#COVID_19uk",
    "#covid19",
    "Covid19",
    "Covid19_DE",
    "#covid19Canada",
    "Covid19DE",
    "Covid19Deutschland",
    "#covid19espana",
    "#covid19france",
    "#covid19Indonesia",
    "#covid19ireland",
    "#covid19uk",
    "#covid19usa",
    "#covid2019",
    "#ForcaCoronaVirus",
    "#infocoronavirus",
    "#kamitidaktakutviruscorona",
    "#nCoV",
    "nCoV",
    "#ncov2019",
    "nCoV2019",
    "NeuerCoronavirus",
    "#NeuerCoronavirus",
    "Nouveau coronavirus",
    "#NouveauCoronavirus",
    "novel coronavirus",
    "#NovelCorona",
    "novelcoronavirus",
    "#novelcoronavirus",
    "#NovelCoronavirus",
    "#NuovoCoronavirus",
    "#ohiocoronavirus",
    "#PánicoPorCoranovirus",
    "#SARSCoV2",
    "#SARSCoV2",
    "the coronas",
    "#thecoronas",
    "#trumpdemic",
    "Virus Corona",
    "#viruscorona",
    "فيروس كورونا",
    "#فيروس_كورونا",
    "#كورونا",
    "#كورونا_الجديد",
    "#कोरोना",
    "कोरोना",
    "कोरोना वायरस",
    "#कोरोना_वायरस",
    "코로나",
    "#코로나",
    "#코로나19",
    "코로나바이러스",
    "#코로나바이러스",
    "コロナ",
    "#コロナ",
    "#コロナウイルス",
    "加油武汉",
    "#加油武汉",
    "#新冠病毒",
    "新冠病毒",
    "#新冠肺炎",
    "新冠肺炎",
    "#新型コロナウイルス",
    "#新型冠状病毒",
    "新型冠状病毒",
    "武汉加油",
    "#武汉加油",
    "#武汉疫情",
    "#武汉肺炎",
    "武汉肺炎",
    "#武漢肺炎",
    "武漢肺炎",
    "疫情",
    "#疫情",
    "#CoronaAlert",
    "#coronavirusUP",
    "#coronavirustelangana",
    "#coronaviruskerala",
    "#coronavirusmumbai",
    "#coronavirusdelhi",
    "#coronavirusmaharashtra",
    "#coronavirusinindia",
    "वूहान",
    "#covid_19ind",
    "#covid19india",
    "coronavirus india",
    "#coronavirusindia",
    "#कोविड_19",
    "#कोविड-१९",
    "#कोरोनावायरस",
    "#bayarealockdown",
    "#stayathomechallenge",
    "#stayhomechallenge",
    "#quarantinelife",
    "#dontbeaspreader",
    "#stayhomechallenge",
    "#howtokeeppeoplehome",
    "#togetherathome",
    "alcool em gel",
    "alcool gel",
    "#alcoolemgel",
    "#alcoolgel",
    "#avoidcrowds",
    "bares cerrados",
    "bares fechados",
    "bars closed",
    "#canceleverything",
    "#CerradMadridYa",
    "clases anuladas",
    "#CLOSENYCPUBLICSCHOOLS",
    "#confinementtotal",
    "#CONVID19",
    "#CoronavirusESP",
    "cuarentena",
    "#cuarentena",
    "#CuarentenaCoronavirus",
    "#cuarentenaYA",
    "dont touch ur face",
    "dont touch your face",
    "#DontBeASpreader",
    "#donttouchyourface",
    "escolas fechadas",
    "escolas fechando",
    "escolas sem aula",
    "escolas sem aulas",
    "#euficoemcasa",
    "evitar el contagio",
    "#ficaemcasa",
    "flatten the curve",
    "flattening the curve",
    "#flatteningthecurve",
    "#flattenthecurve",
    "#FrenaLaCurva",
    "Hand sanitizer",
    "#Handsanitizer",
    "#HoldTheVirus",
    "lava tu manos",
    "#lavatumanos",
    "lave as maos",
    "#laveasmaos",
    "#lockdown",
    "lockdown",
    "#pandemic",
    "pandemic",
    "#panicbuying",
    "#panickbuing",
    "quarantaine",
    "#quarantine",
    "quarantine",
    "#QuarantineAndChill",
    "quarantined",
    "quarentena",
    "#quarentena",
    "#quarentine",
    "#quarentined",
    "quarentined",
    "#quarentinelife",
    "#quedateencasa",
    "#remotework",
    "#remoteworking",
    "restaurantes cerrados",
    "restaurantes fechados",
    "restaurants closed",
    "#selfisolating",
    "#SiMeContagioYo",
    "social distancing",
    "#socialdistance",
    "#socialdistancing",
    "#socialdistancingnow",
    "#socialdistnacing",
    "#stayathome",
    "#stayathome",
    "#stayhome",
    "#stayhome",
    "#stayhomechallenge",
    "#stayhomesavelives",
    "#StayTheFHome",
    "#StayTheFuckHome",
    "#suspendanlasclases",
    "teletrabajo",
    "#teletrabajo",
    "#ToiletPaperApocalypse",
    "#toiletpaperpanic",
    "trabajadores a la calle",
    "trabajar desde casa",
    "#trabajardesdecasa",
    "trabalhando de casa",
    "trabalhar de casa",
    "wash ur hands",
    "wash your hands",
    "#washurhands",
    "#washyourhands",
    "#WashYourHandsAgain",
    "#wfh",
    "work from home",
    "#workfromhome",
    "working from home",
    "#workingfromhome",
    "#yomequedoencasa",
    "#2019_ncov",
    "#21dayslockdown",
    "#5baje5minute",
    "#9minute9baje",
    "#9minutesforindia",
    "#9बजे9मिनट",
    "#AislamientoObligatorio",
    "#aksiberantasCovid19",
    "#AlertaCOVID19SV",
    "#ampliarlacuarentenaes",
    "#auxilioemergencial",
    "#BersamaMelawanCorona",
    "#bersatulawancovid19",
    "#bloqueioderuas",
    "#Bogotaencasa",
    "#bolsonarogenocida",
    "#BreakCorona",
    "#cadeostestes",
    "#californialockdown",
    "#californiaquarantine",
    "#californiashutdown",
    "#calockdown",
    "#capitaocorona",
    "#CegahTangkalCorona",
    "#chegadequarentena",
    "#clapforourcarers",
    "#ClubQuarantine",
    "#CoronaChainScare",
    "#CoronaCitizenResponsibility",
    "#CoronaCrises",
    "#coronacrises",
    "#CoronaCrisis",
    "#coronafreepakistan",
    "#CoronaInPakistan",
    "#coronakrise",
    "#coronalockdown",
    "#coronanasperiferias",
    "#coronapandemie",
    "#coronapandemie",
    "#CoronaStopKaroNa",
    "#coronaupdate",
    "#coronaupdatesindia",
    "#CoronaVillains",
    "#coronaviru",
    "#CoronavirusBillUK",
    "#CoronaVirusFromMinorChastisement",
    "#coronavirusinsa",
    "#coronavirusitalia",
    "#coronavirusitaly",
    "#coronaviruslombardia",
    "#coronavirusoubreak",
    "#coronavirusplantao",
    "#CoronavirusPlantao",
    "#CoronaVirusSA",
    "#CoronavirusSchweiz",
    "#coronavirussouthafrica",
    "#CoronavirusSuisse",
    "#CoronavirusSwitzerland",
    "#coronavoucher",
    "#coronawarriors",
    "#coronawarriors",
    "#coronazeit",
    "#coronovirus",
    "#coronvirus",
    "#corronavirus",
    "#Covid19_CH",
    "#covid19brasil",
    "#Covid19CH",
    "#covid19ecuador",
    "#Covid19InSA",
    "#COVID19italia",
    "#covid19out",
    "#Covid19Schweiz",
    "#covid19southafrica",
    "#covidactnow",
    "#covideos",
    "#covididiots",
    "#covidiots",
    "#covidsafe",
    "#CuarentenaHastaJunioEs",
    "#CuarentenaInformando",
    "#cuarentenametadata",
    "#cubaporlasalud",
    "#cubasalvavidas",
    "#CubriendoElCoronavirus",
    "#CurfewInIndia",
    "#CurfewInIndia",
    "#CuronaVairus",
    "#curonavirus",
    "#depoisdaquarentenaeu",
    "#dirumahaja",
    "#disciplinaparavolver",
    "#disiplincegahcorona",
    "#ecuadorencrisis",
    "#ecuadorenemergencia",
    "#eunaquarentena",
    "#FightCoronaWithJokowi",
    "#fiqueemcasa",
    "#FlexibilizarElAislamientoEs",
    "#frontline_warriors_intern",
    "#frontlineheroes",
    "#frontlineworkers",
    "#frontlineworkersappreciation",
    "#GerakanSocialDistancing",
    "#homeschool",
    "#homeschooling",
    "#HomeTasking",
    "#hydroxychloroquine",
    "#indiafightcorona",
    "#indiaprotectdoctors",
    "#indonesialawancorona",
    "#indonesialawancovid19",
    "#JagaDiriJagaJarak",
    "#JanataCurfewMarch22",
    "#JantaCurfewChallenge",
    "#KanikaCoronaRow",
    "#KanikaKaCoronaCrime",
    "#koronaindonesia",
    "#koronavirusIndonesia",
    "#LaPrevenciónEstáEnTusManos",
    "#LawanCorona",
    "#LawanCoronaBersama",
    "#lawancovid19",
    "#LawanCovid19",
    "#LetsDefeatCOVID19Together",
    "#Lockdowhustle",
    "#lockdown21",
    "#LockdownEnd",
    "#LockdownNow",
    "#lockdowntillmay3",
    "#losangeleslockdown",
    "#mascaras",
    "#mascarasalva",
    "#mascarilla",
    "#mascarillas",
    "#mascarillassolidarias",
    "#masks4all",
    "#maskuplagos",
    "#micasaesmiplaza",
    "#michiganshutdown",
    "#ModiKiBaatMano    ",
    "#mp927",
    "#mpdafome",
    "#mpdamorte",
    "#mpdobolsonaro",
    "#mumbailockdown",
    "#n95",
    "#NeuerCoronavirusSchweiz",
    "#NoAlAislamientoInteligente",
    "#NotDying4WallStreet",
    "#notessential",
    "#obrasilnaopodeparar",
    "#OBrasilnaoVaiParar",
    "#obrasilvaiparar",
    "#OneTeamFromHome",
    "#onlineclasses",
    "#ParemosElVirus",
    "#PMCares",
    "#PPE",
    "#ppeshortage",
    "#pralernaquarentena",
    "#PrioridadDineroOSalud",
    "#QuarantineMoneyMakingIdeas",
    "#quaratinelife",
    "#quarentenabrasil",
    "#quarentenaLGBTQ",
    "#quarentenou",
    "#quaretenabrasil",
    "#QuaronaVirus",
    "#ReceitasDaQuarentena",
    "#remdesivir",
    "#SCNaoQuerMorrer",
    "#selfemployedmattertoo",
    "#SendUsBackHome",
    "#ShamblesStayAtHome",
    "#sideeffectsofquarantinelife",
    "#Social_Distancing",
    "#sosecuador",
    "#spcontraocoronavirus",
    "#SRKDonatesForCovid",
    "#stayathomeorder",
    "#StayAtHomeReadABook",
    "#StayAtHomeSaveLives",
    "#stayhomestaysafe",
    "#suspendonlineclasses",
    "#taxarfortunassalvarvidas",
    "#TaxarFortunasSalvarVidas",
    "#TaxarFortunasSalvarVidas",
    "#testesmasivosja",
    "#testesmassivosja",
    "#ThaliBajao",
    "#thankyouwarriors",
    "#UKCoronavirusBill",
    "#uklockdown",
    "#UNExigimosGarantiasLaborales",
    "#unidosvenceremos",
    "#UNSuspendanClasesOParamos",
    "#unsuspendanclasesya",
    "#UNSuspendanlasClasesOParamos",
    "#usemascara",
    "#vaipassar",
    "#vegasshutdown",
    "#viviremosyvenceremos",
    "#VivirEnCuarentenaEs",
    "#WarAgainstVirus",
    "#waragainstvirus",
    "#wearamask",
    "#WhenCoronaVirusIsOver",
    "#WhoPaysForCovid",
    "#WorkingFromHomeLife",
    "#workingfromhometips",
    "#अंधेर_नगरी_चौपट_राजा",
    "#मोदीजी_हम_दीप_नहीं_जलाएंगे",
    "#ウイルス付着",
    "#うちで過ごそう",
    "#おうち時間",
    "#コロナに負けるな",
    "#コロリンピック",
    "#ステイホーム",
    "#ソーシャルディスタンス",
    "#ロックダウン",
    "#外出禁止",
    "#外出自粛",
    "#新しい生活様式",
    "#東京コロリンピック",
    "#特別定額給付金",
    "#緊急事態宣言",
    "aula online",
    "auxilio emergencial",
    "Bloody Diwali",
    "bloqueio de ruas",
    "bloqueio de vias",
    "bloqueio em vias",
    "bloqueou as ruas",
    "coron virus",
    "corona voucher",
    "coronaa virus",
    "coronga vairus",
    "corono virus",
    "coronovirus",
    "corrona virus",
    "Curona Vairus",
    "curona virus",
    "Diwali In April",
    "Ecoronavirusescuador",
    "en primera linea",
    "essencial service",
    "essencial services",
    "essential service",
    "essential services",
    "face shield",
    "face shields",
    "Frontline",
    "hand sanitisers",
    "health worker",
    "health workers",
    "homeschooling",
    "hydroxychloroquine",
    "India for 21",
    "India Hum Honge Kamyab",
    "linha de frente",
    "mascara",
    "mascarilla",
    "mascarillas",
    "mascarillas desechables",
    "n95 mask",
    "no mask",
    "personal protective equipment",
    "PPE",
    "primera línea de la salud",
    "quarentenou",
    "Quarona Virus",
    "remdesivir",
    "servicio esencial",
    "servicios esenciales",
    "serviços essenciais",
    "Shankh",
    "trabajador sanitario",
    "Trabajadora sanitaria",
    "trabajadores de la salud",
    "trabalhador essencial",
    "trabalhadores essenciais",
    "ウイルス付着",
    "コロナウィルス",
    "コロリンピック",
    "ソーシャルディスタンス",
    "ロックダウン",
    "外出禁止",
    "外出自粛",
    "定額給付金",
    "新しい生活様式",
    "緊急事態宣言",
    "#LockdownLife",
    "#LockdownExtended",
    "#lockdowneffect",
    "#mortonaocompra",
    "#isolamentoparcial",
    "isolamento parcial",
    "#lockdownparcial",
    "#mortonaovota",
    "passaportes de imunidade",
    "imunidade de rebanho",
    "#UnitedAgainstCoronavirus",
    "#CovidISSNAF",
    "testes em humanos",
    "human trials",
    "gripezinha",
    "the virus"
]
